blank_issues_enabled: true

contact_links:
  - name: Cog Support Discord Server
    url: https://discord.gg/GET4DVk
    about: You can also find me in #support_ob13-cogs for support with my cogs or reporting bugs/errors.
